package com.github.pakka_papad.ui.accent_colours.elm

import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme


val ElmLightColors = lightColorScheme(
    primary = elm_theme_light_primary,
    onPrimary = elm_theme_light_onPrimary,
    primaryContainer = elm_theme_light_primaryContainer,
    onPrimaryContainer = elm_theme_light_onPrimaryContainer,
    secondary = elm_theme_light_secondary,
    onSecondary = elm_theme_light_onSecondary,
    secondaryContainer = elm_theme_light_secondaryContainer,
    onSecondaryContainer = elm_theme_light_onSecondaryContainer,
    tertiary = elm_theme_light_tertiary,
    onTertiary = elm_theme_light_onTertiary,
    tertiaryContainer = elm_theme_light_tertiaryContainer,
    onTertiaryContainer = elm_theme_light_onTertiaryContainer,
    error = elm_theme_light_error,
    errorContainer = elm_theme_light_errorContainer,
    onError = elm_theme_light_onError,
    onErrorContainer = elm_theme_light_onErrorContainer,
    background = elm_theme_light_background,
    onBackground = elm_theme_light_onBackground,
    surface = elm_theme_light_surface,
    onSurface = elm_theme_light_onSurface,
    surfaceVariant = elm_theme_light_surfaceVariant,
    onSurfaceVariant = elm_theme_light_onSurfaceVariant,
    outline = elm_theme_light_outline,
    inverseOnSurface = elm_theme_light_inverseOnSurface,
    inverseSurface = elm_theme_light_inverseSurface,
    inversePrimary = elm_theme_light_inversePrimary,
    surfaceTint = elm_theme_light_surfaceTint,
)


val ElmDarkColors = darkColorScheme(
    primary = elm_theme_dark_primary,
    onPrimary = elm_theme_dark_onPrimary,
    primaryContainer = elm_theme_dark_primaryContainer,
    onPrimaryContainer = elm_theme_dark_onPrimaryContainer,
    secondary = elm_theme_dark_secondary,
    onSecondary = elm_theme_dark_onSecondary,
    secondaryContainer = elm_theme_dark_secondaryContainer,
    onSecondaryContainer = elm_theme_dark_onSecondaryContainer,
    tertiary = elm_theme_dark_tertiary,
    onTertiary = elm_theme_dark_onTertiary,
    tertiaryContainer = elm_theme_dark_tertiaryContainer,
    onTertiaryContainer = elm_theme_dark_onTertiaryContainer,
    error = elm_theme_dark_error,
    errorContainer = elm_theme_dark_errorContainer,
    onError = elm_theme_dark_onError,
    onErrorContainer = elm_theme_dark_onErrorContainer,
    background = elm_theme_dark_background,
    onBackground = elm_theme_dark_onBackground,
    surface = elm_theme_dark_surface,
    onSurface = elm_theme_dark_onSurface,
    surfaceVariant = elm_theme_dark_surfaceVariant,
    onSurfaceVariant = elm_theme_dark_onSurfaceVariant,
    outline = elm_theme_dark_outline,
    inverseOnSurface = elm_theme_dark_inverseOnSurface,
    inverseSurface = elm_theme_dark_inverseSurface,
    inversePrimary = elm_theme_dark_inversePrimary,
    surfaceTint = elm_theme_dark_surfaceTint,
)