package com.github.pakka_papad.ui.accent_colours.jacksons_purple
import androidx.compose.ui.graphics.Color

val jacksons_purple_theme_light_primary = Color(0xFF4853BD)
val jacksons_purple_theme_light_onPrimary = Color(0xFFFFFFFF)
val jacksons_purple_theme_light_primaryContainer = Color(0xFFDFE0FF)
val jacksons_purple_theme_light_onPrimaryContainer = Color(0xFF000767)
val jacksons_purple_theme_light_secondary = Color(0xFF5C5D72)
val jacksons_purple_theme_light_onSecondary = Color(0xFFFFFFFF)
val jacksons_purple_theme_light_secondaryContainer = Color(0xFFE1E0F9)
val jacksons_purple_theme_light_onSecondaryContainer = Color(0xFF181A2C)
val jacksons_purple_theme_light_tertiary = Color(0xFF78536B)
val jacksons_purple_theme_light_onTertiary = Color(0xFFFFFFFF)
val jacksons_purple_theme_light_tertiaryContainer = Color(0xFFFFD7EF)
val jacksons_purple_theme_light_onTertiaryContainer = Color(0xFF2E1126)
val jacksons_purple_theme_light_error = Color(0xFFBA1A1A)
val jacksons_purple_theme_light_errorContainer = Color(0xFFFFDAD6)
val jacksons_purple_theme_light_onError = Color(0xFFFFFFFF)
val jacksons_purple_theme_light_onErrorContainer = Color(0xFF410002)
val jacksons_purple_theme_light_background = Color(0xFFFFFBFF)
val jacksons_purple_theme_light_onBackground = Color(0xFF1B1B1F)
val jacksons_purple_theme_light_surface = Color(0xFFFFFBFF)
val jacksons_purple_theme_light_onSurface = Color(0xFF1B1B1F)
val jacksons_purple_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val jacksons_purple_theme_light_onSurfaceVariant = Color(0xFF46464F)
val jacksons_purple_theme_light_outline = Color(0xFF777680)
val jacksons_purple_theme_light_inverseOnSurface = Color(0xFFF3F0F4)
val jacksons_purple_theme_light_inverseSurface = Color(0xFF303034)
val jacksons_purple_theme_light_inversePrimary = Color(0xFFBDC2FF)
val jacksons_purple_theme_light_surfaceTint = Color(0xFF4853BD)

val jacksons_purple_theme_dark_primary = Color(0xFFBDC2FF)
val jacksons_purple_theme_dark_onPrimary = Color(0xFF121E8E)
val jacksons_purple_theme_dark_primaryContainer = Color(0xFF2E39A4)
val jacksons_purple_theme_dark_onPrimaryContainer = Color(0xFFDFE0FF)
val jacksons_purple_theme_dark_secondary = Color(0xFFC4C4DD)
val jacksons_purple_theme_dark_onSecondary = Color(0xFF2D2F42)
val jacksons_purple_theme_dark_secondaryContainer = Color(0xFF444559)
val jacksons_purple_theme_dark_onSecondaryContainer = Color(0xFFE1E0F9)
val jacksons_purple_theme_dark_tertiary = Color(0xFFE7B9D6)
val jacksons_purple_theme_dark_onTertiary = Color(0xFF45263C)
val jacksons_purple_theme_dark_tertiaryContainer = Color(0xFF5E3C53)
val jacksons_purple_theme_dark_onTertiaryContainer = Color(0xFFFFD7EF)
val jacksons_purple_theme_dark_error = Color(0xFFFFB4AB)
val jacksons_purple_theme_dark_errorContainer = Color(0xFF93000A)
val jacksons_purple_theme_dark_onError = Color(0xFF690005)
val jacksons_purple_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val jacksons_purple_theme_dark_background = Color(0xFF1B1B1F)
val jacksons_purple_theme_dark_onBackground = Color(0xFFE4E1E6)
val jacksons_purple_theme_dark_surface = Color(0xFF1B1B1F)
val jacksons_purple_theme_dark_onSurface = Color(0xFFE4E1E6)
val jacksons_purple_theme_dark_surfaceVariant = Color(0xFF46464F)
val jacksons_purple_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val jacksons_purple_theme_dark_outline = Color(0xFF91909A)
val jacksons_purple_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val jacksons_purple_theme_dark_inverseSurface = Color(0xFFE4E1E6)
val jacksons_purple_theme_dark_inversePrimary = Color(0xFF4853BD)
val jacksons_purple_theme_dark_surfaceTint = Color(0xFFBDC2FF)


val jacksons_purple_seed = Color(0xFF242F9B)
