package com.github.pakka_papad.ui.accent_colours.malibu

import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme


val MalibuLightColors = lightColorScheme(
    primary = malibu_theme_light_primary,
    onPrimary = malibu_theme_light_onPrimary,
    primaryContainer = malibu_theme_light_primaryContainer,
    onPrimaryContainer = malibu_theme_light_onPrimaryContainer,
    secondary = malibu_theme_light_secondary,
    onSecondary = malibu_theme_light_onSecondary,
    secondaryContainer = malibu_theme_light_secondaryContainer,
    onSecondaryContainer = malibu_theme_light_onSecondaryContainer,
    tertiary = malibu_theme_light_tertiary,
    onTertiary = malibu_theme_light_onTertiary,
    tertiaryContainer = malibu_theme_light_tertiaryContainer,
    onTertiaryContainer = malibu_theme_light_onTertiaryContainer,
    error = malibu_theme_light_error,
    errorContainer = malibu_theme_light_errorContainer,
    onError = malibu_theme_light_onError,
    onErrorContainer = malibu_theme_light_onErrorContainer,
    background = malibu_theme_light_background,
    onBackground = malibu_theme_light_onBackground,
    surface = malibu_theme_light_surface,
    onSurface = malibu_theme_light_onSurface,
    surfaceVariant = malibu_theme_light_surfaceVariant,
    onSurfaceVariant = malibu_theme_light_onSurfaceVariant,
    outline = malibu_theme_light_outline,
    inverseOnSurface = malibu_theme_light_inverseOnSurface,
    inverseSurface = malibu_theme_light_inverseSurface,
    inversePrimary = malibu_theme_light_inversePrimary,
    surfaceTint = malibu_theme_light_surfaceTint,
)


val MalibuDarkColors = darkColorScheme(
    primary = malibu_theme_dark_primary,
    onPrimary = malibu_theme_dark_onPrimary,
    primaryContainer = malibu_theme_dark_primaryContainer,
    onPrimaryContainer = malibu_theme_dark_onPrimaryContainer,
    secondary = malibu_theme_dark_secondary,
    onSecondary = malibu_theme_dark_onSecondary,
    secondaryContainer = malibu_theme_dark_secondaryContainer,
    onSecondaryContainer = malibu_theme_dark_onSecondaryContainer,
    tertiary = malibu_theme_dark_tertiary,
    onTertiary = malibu_theme_dark_onTertiary,
    tertiaryContainer = malibu_theme_dark_tertiaryContainer,
    onTertiaryContainer = malibu_theme_dark_onTertiaryContainer,
    error = malibu_theme_dark_error,
    errorContainer = malibu_theme_dark_errorContainer,
    onError = malibu_theme_dark_onError,
    onErrorContainer = malibu_theme_dark_onErrorContainer,
    background = malibu_theme_dark_background,
    onBackground = malibu_theme_dark_onBackground,
    surface = malibu_theme_dark_surface,
    onSurface = malibu_theme_dark_onSurface,
    surfaceVariant = malibu_theme_dark_surfaceVariant,
    onSurfaceVariant = malibu_theme_dark_onSurfaceVariant,
    outline = malibu_theme_dark_outline,
    inverseOnSurface = malibu_theme_dark_inverseOnSurface,
    inverseSurface = malibu_theme_dark_inverseSurface,
    inversePrimary = malibu_theme_dark_inversePrimary,
    surfaceTint = malibu_theme_dark_surfaceTint,
)