package com.github.pakka_papad.ui.accent_colours.malibu
import androidx.compose.ui.graphics.Color

val malibu_theme_light_primary = Color(0xFF00658E)
val malibu_theme_light_onPrimary = Color(0xFFFFFFFF)
val malibu_theme_light_primaryContainer = Color(0xFFC7E7FF)
val malibu_theme_light_onPrimaryContainer = Color(0xFF001E2E)
val malibu_theme_light_secondary = Color(0xFF4F616E)
val malibu_theme_light_onSecondary = Color(0xFFFFFFFF)
val malibu_theme_light_secondaryContainer = Color(0xFFD2E5F5)
val malibu_theme_light_onSecondaryContainer = Color(0xFF0B1D29)
val malibu_theme_light_tertiary = Color(0xFF63597C)
val malibu_theme_light_onTertiary = Color(0xFFFFFFFF)
val malibu_theme_light_tertiaryContainer = Color(0xFFE8DDFF)
val malibu_theme_light_onTertiaryContainer = Color(0xFF1E1635)
val malibu_theme_light_error = Color(0xFFBA1A1A)
val malibu_theme_light_errorContainer = Color(0xFFFFDAD6)
val malibu_theme_light_onError = Color(0xFFFFFFFF)
val malibu_theme_light_onErrorContainer = Color(0xFF410002)
val malibu_theme_light_background = Color(0xFFFCFCFF)
val malibu_theme_light_onBackground = Color(0xFF191C1E)
val malibu_theme_light_surface = Color(0xFFFCFCFF)
val malibu_theme_light_onSurface = Color(0xFF191C1E)
val malibu_theme_light_surfaceVariant = Color(0xFFDDE3EA)
val malibu_theme_light_onSurfaceVariant = Color(0xFF41484D)
val malibu_theme_light_outline = Color(0xFF71787E)
val malibu_theme_light_inverseOnSurface = Color(0xFFF0F1F3)
val malibu_theme_light_inverseSurface = Color(0xFF2E3133)
val malibu_theme_light_inversePrimary = Color(0xFF84CFFF)
val malibu_theme_light_surfaceTint = Color(0xFF00658E)

val malibu_theme_dark_primary = Color(0xFF84CFFF)
val malibu_theme_dark_onPrimary = Color(0xFF00344C)
val malibu_theme_dark_primaryContainer = Color(0xFF004C6C)
val malibu_theme_dark_onPrimaryContainer = Color(0xFFC7E7FF)
val malibu_theme_dark_secondary = Color(0xFFB6C9D8)
val malibu_theme_dark_onSecondary = Color(0xFF21323E)
val malibu_theme_dark_secondaryContainer = Color(0xFF374955)
val malibu_theme_dark_onSecondaryContainer = Color(0xFFD2E5F5)
val malibu_theme_dark_tertiary = Color(0xFFCDC0E9)
val malibu_theme_dark_onTertiary = Color(0xFF342B4B)
val malibu_theme_dark_tertiaryContainer = Color(0xFF4B4263)
val malibu_theme_dark_onTertiaryContainer = Color(0xFFE8DDFF)
val malibu_theme_dark_error = Color(0xFFFFB4AB)
val malibu_theme_dark_errorContainer = Color(0xFF93000A)
val malibu_theme_dark_onError = Color(0xFF690005)
val malibu_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val malibu_theme_dark_background = Color(0xFF191C1E)
val malibu_theme_dark_onBackground = Color(0xFFE2E2E5)
val malibu_theme_dark_surface = Color(0xFF191C1E)
val malibu_theme_dark_onSurface = Color(0xFFE2E2E5)
val malibu_theme_dark_surfaceVariant = Color(0xFF41484D)
val malibu_theme_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val malibu_theme_dark_outline = Color(0xFF8B9198)
val malibu_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val malibu_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val malibu_theme_dark_inversePrimary = Color(0xFF00658E)
val malibu_theme_dark_surfaceTint = Color(0xFF84CFFF)


val malibu_seed = Color(0xFF89CFFD)
