package com.github.pakka_papad.ui.accent_colours.default

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val DefaultLightColors = lightColorScheme(
    primary = default_theme_light_primary,
    onPrimary = default_theme_light_onPrimary,
    primaryContainer = default_theme_light_primaryContainer,
    onPrimaryContainer = default_theme_light_onPrimaryContainer,
    secondary = default_theme_light_secondary,
    onSecondary = default_theme_light_onSecondary,
    secondaryContainer = default_theme_light_secondaryContainer,
    onSecondaryContainer = default_theme_light_onSecondaryContainer,
    tertiary = default_theme_light_tertiary,
    onTertiary = default_theme_light_onTertiary,
    tertiaryContainer = default_theme_light_tertiaryContainer,
    onTertiaryContainer = default_theme_light_onTertiaryContainer,
    error = default_theme_light_error,
    errorContainer = default_theme_light_errorContainer,
    onError = default_theme_light_onError,
    onErrorContainer = default_theme_light_onErrorContainer,
    background = default_theme_light_background,
    onBackground = default_theme_light_onBackground,
    surface = default_theme_light_surface,
    onSurface = default_theme_light_onSurface,
    surfaceVariant = default_theme_light_surfaceVariant,
    onSurfaceVariant = default_theme_light_onSurfaceVariant,
    outline = default_theme_light_outline,
    inverseOnSurface = default_theme_light_inverseOnSurface,
    inverseSurface = default_theme_light_inverseSurface,
    inversePrimary = default_theme_light_inversePrimary,
    surfaceTint = default_theme_light_surfaceTint,
)


val DefaultDarkColors = darkColorScheme(
    primary = default_theme_dark_primary,
    onPrimary = default_theme_dark_onPrimary,
    primaryContainer = default_theme_dark_primaryContainer,
    onPrimaryContainer = default_theme_dark_onPrimaryContainer,
    secondary = default_theme_dark_secondary,
    onSecondary = default_theme_dark_onSecondary,
    secondaryContainer = default_theme_dark_secondaryContainer,
    onSecondaryContainer = default_theme_dark_onSecondaryContainer,
    tertiary = default_theme_dark_tertiary,
    onTertiary = default_theme_dark_onTertiary,
    tertiaryContainer = default_theme_dark_tertiaryContainer,
    onTertiaryContainer = default_theme_dark_onTertiaryContainer,
    error = default_theme_dark_error,
    errorContainer = default_theme_dark_errorContainer,
    onError = default_theme_dark_onError,
    onErrorContainer = default_theme_dark_onErrorContainer,
    background = default_theme_dark_background,
    onBackground = default_theme_dark_onBackground,
    surface = default_theme_dark_surface,
    onSurface = default_theme_dark_onSurface,
    surfaceVariant = default_theme_dark_surfaceVariant,
    onSurfaceVariant = default_theme_dark_onSurfaceVariant,
    outline = default_theme_dark_outline,
    inverseOnSurface = default_theme_dark_inverseOnSurface,
    inverseSurface = default_theme_dark_inverseSurface,
    inversePrimary = default_theme_dark_inversePrimary,
    surfaceTint = default_theme_dark_surfaceTint,
)