package com.github.pakka_papad.ui.accent_colours.default

import androidx.compose.ui.graphics.Color

val default_theme_light_primary = Color(0xFF006D40)
val default_theme_light_onPrimary = Color(0xFFFFFFFF)
val default_theme_light_primaryContainer = Color(0xFF69FDAD)
val default_theme_light_onPrimaryContainer = Color(0xFF002110)
val default_theme_light_secondary = Color(0xFF4E6354)
val default_theme_light_onSecondary = Color(0xFFFFFFFF)
val default_theme_light_secondaryContainer = Color(0xFFD1E8D5)
val default_theme_light_onSecondaryContainer = Color(0xFF0C1F14)
val default_theme_light_tertiary = Color(0xFF3B6470)
val default_theme_light_onTertiary = Color(0xFFFFFFFF)
val default_theme_light_tertiaryContainer = Color(0xFFBFE9F8)
val default_theme_light_onTertiaryContainer = Color(0xFF001F27)
val default_theme_light_error = Color(0xFFBA1A1A)
val default_theme_light_errorContainer = Color(0xFFFFDAD6)
val default_theme_light_onError = Color(0xFFFFFFFF)
val default_theme_light_onErrorContainer = Color(0xFF410002)
val default_theme_light_background = Color(0xFFFBFDF8)
val default_theme_light_onBackground = Color(0xFF191C1A)
val default_theme_light_surface = Color(0xFFFBFDF8)
val default_theme_light_onSurface = Color(0xFF191C1A)
val default_theme_light_surfaceVariant = Color(0xFFDCE5DB)
val default_theme_light_onSurfaceVariant = Color(0xFF414942)
val default_theme_light_outline = Color(0xFF717972)
val default_theme_light_inverseOnSurface = Color(0xFFF0F1EC)
val default_theme_light_inverseSurface = Color(0xFF2E312E)
val default_theme_light_inversePrimary = Color(0xFF47E093)
val default_theme_light_surfaceTint = Color(0xFF006D40)

val default_theme_dark_primary = Color(0xFF47E093)
val default_theme_dark_onPrimary = Color(0xFF00391F)
val default_theme_dark_primaryContainer = Color(0xFF00522F)
val default_theme_dark_onPrimaryContainer = Color(0xFF69FDAD)
val default_theme_dark_secondary = Color(0xFFB5CCBA)
val default_theme_dark_onSecondary = Color(0xFF213528)
val default_theme_dark_secondaryContainer = Color(0xFF374B3D)
val default_theme_dark_onSecondaryContainer = Color(0xFFD1E8D5)
val default_theme_dark_tertiary = Color(0xFFA3CDDB)
val default_theme_dark_onTertiary = Color(0xFF033541)
val default_theme_dark_tertiaryContainer = Color(0xFF224C58)
val default_theme_dark_onTertiaryContainer = Color(0xFFBFE9F8)
val default_theme_dark_error = Color(0xFFFFB4AB)
val default_theme_dark_errorContainer = Color(0xFF93000A)
val default_theme_dark_onError = Color(0xFF690005)
val default_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val default_theme_dark_background = Color(0xFF191C1A)
val default_theme_dark_onBackground = Color(0xFFE1E3DE)
val default_theme_dark_surface = Color(0xFF191C1A)
val default_theme_dark_onSurface = Color(0xFFE1E3DE)
val default_theme_dark_surfaceVariant = Color(0xFF414942)
val default_theme_dark_onSurfaceVariant = Color(0xFFC0C9C0)
val default_theme_dark_outline = Color(0xFF8A938B)
val default_theme_dark_inverseOnSurface = Color(0xFF191C1A)
val default_theme_dark_inverseSurface = Color(0xFFE1E3DE)
val default_theme_dark_inversePrimary = Color(0xFF006D40)
val default_theme_dark_surfaceTint = Color(0xFF47E093)


val default_seed = Color(0xFF17C379)