package com.github.pakka_papad.ui.accent_colours.magenta

import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme


val MagentaLightColors = lightColorScheme(
    primary = magenta_theme_light_primary,
    onPrimary = magenta_theme_light_onPrimary,
    primaryContainer = magenta_theme_light_primaryContainer,
    onPrimaryContainer = magenta_theme_light_onPrimaryContainer,
    secondary = magenta_theme_light_secondary,
    onSecondary = magenta_theme_light_onSecondary,
    secondaryContainer = magenta_theme_light_secondaryContainer,
    onSecondaryContainer = magenta_theme_light_onSecondaryContainer,
    tertiary = magenta_theme_light_tertiary,
    onTertiary = magenta_theme_light_onTertiary,
    tertiaryContainer = magenta_theme_light_tertiaryContainer,
    onTertiaryContainer = magenta_theme_light_onTertiaryContainer,
    error = magenta_theme_light_error,
    errorContainer = magenta_theme_light_errorContainer,
    onError = magenta_theme_light_onError,
    onErrorContainer = magenta_theme_light_onErrorContainer,
    background = magenta_theme_light_background,
    onBackground = magenta_theme_light_onBackground,
    surface = magenta_theme_light_surface,
    onSurface = magenta_theme_light_onSurface,
    surfaceVariant = magenta_theme_light_surfaceVariant,
    onSurfaceVariant = magenta_theme_light_onSurfaceVariant,
    outline = magenta_theme_light_outline,
    inverseOnSurface = magenta_theme_light_inverseOnSurface,
    inverseSurface = magenta_theme_light_inverseSurface,
    inversePrimary = magenta_theme_light_inversePrimary,
    surfaceTint = magenta_theme_light_surfaceTint,
)


val MagentaDarkColors = darkColorScheme(
    primary = magenta_theme_dark_primary,
    onPrimary = magenta_theme_dark_onPrimary,
    primaryContainer = magenta_theme_dark_primaryContainer,
    onPrimaryContainer = magenta_theme_dark_onPrimaryContainer,
    secondary = magenta_theme_dark_secondary,
    onSecondary = magenta_theme_dark_onSecondary,
    secondaryContainer = magenta_theme_dark_secondaryContainer,
    onSecondaryContainer = magenta_theme_dark_onSecondaryContainer,
    tertiary = magenta_theme_dark_tertiary,
    onTertiary = magenta_theme_dark_onTertiary,
    tertiaryContainer = magenta_theme_dark_tertiaryContainer,
    onTertiaryContainer = magenta_theme_dark_onTertiaryContainer,
    error = magenta_theme_dark_error,
    errorContainer = magenta_theme_dark_errorContainer,
    onError = magenta_theme_dark_onError,
    onErrorContainer = magenta_theme_dark_onErrorContainer,
    background = magenta_theme_dark_background,
    onBackground = magenta_theme_dark_onBackground,
    surface = magenta_theme_dark_surface,
    onSurface = magenta_theme_dark_onSurface,
    surfaceVariant = magenta_theme_dark_surfaceVariant,
    onSurfaceVariant = magenta_theme_dark_onSurfaceVariant,
    outline = magenta_theme_dark_outline,
    inverseOnSurface = magenta_theme_dark_inverseOnSurface,
    inverseSurface = magenta_theme_dark_inverseSurface,
    inversePrimary = magenta_theme_dark_inversePrimary,
    surfaceTint = magenta_theme_dark_surfaceTint,
)