package com.github.pakka_papad.ui.accent_colours.magenta
import androidx.compose.ui.graphics.Color

val magenta_theme_light_primary = Color(0xFFA62E72)
val magenta_theme_light_onPrimary = Color(0xFFFFFFFF)
val magenta_theme_light_primaryContainer = Color(0xFFFFD8E7)
val magenta_theme_light_onPrimaryContainer = Color(0xFF3D0025)
val magenta_theme_light_secondary = Color(0xFF725762)
val magenta_theme_light_onSecondary = Color(0xFFFFFFFF)
val magenta_theme_light_secondaryContainer = Color(0xFFFED9E6)
val magenta_theme_light_onSecondaryContainer = Color(0xFF2A151F)
val magenta_theme_light_tertiary = Color(0xFF7E5539)
val magenta_theme_light_onTertiary = Color(0xFFFFFFFF)
val magenta_theme_light_tertiaryContainer = Color(0xFFFFDCC7)
val magenta_theme_light_onTertiaryContainer = Color(0xFF301401)
val magenta_theme_light_error = Color(0xFFBA1A1A)
val magenta_theme_light_errorContainer = Color(0xFFFFDAD6)
val magenta_theme_light_onError = Color(0xFFFFFFFF)
val magenta_theme_light_onErrorContainer = Color(0xFF410002)
val magenta_theme_light_background = Color(0xFFFFFBFF)
val magenta_theme_light_onBackground = Color(0xFF1F1A1C)
val magenta_theme_light_surface = Color(0xFFFFFBFF)
val magenta_theme_light_onSurface = Color(0xFF1F1A1C)
val magenta_theme_light_surfaceVariant = Color(0xFFF1DEE3)
val magenta_theme_light_onSurfaceVariant = Color(0xFF504348)
val magenta_theme_light_outline = Color(0xFF827378)
val magenta_theme_light_inverseOnSurface = Color(0xFFF9EEF0)
val magenta_theme_light_inverseSurface = Color(0xFF352F31)
val magenta_theme_light_inversePrimary = Color(0xFFFFAFD2)
val magenta_theme_light_surfaceTint = Color(0xFFA62E72)

val magenta_theme_dark_primary = Color(0xFFFFAFD2)
val magenta_theme_dark_onPrimary = Color(0xFF63003F)
val magenta_theme_dark_primaryContainer = Color(0xFF870F59)
val magenta_theme_dark_onPrimaryContainer = Color(0xFFFFD8E7)
val magenta_theme_dark_secondary = Color(0xFFE0BDCA)
val magenta_theme_dark_onSecondary = Color(0xFF412A34)
val magenta_theme_dark_secondaryContainer = Color(0xFF59404A)
val magenta_theme_dark_onSecondaryContainer = Color(0xFFFED9E6)
val magenta_theme_dark_tertiary = Color(0xFFF2BB98)
val magenta_theme_dark_onTertiary = Color(0xFF492810)
val magenta_theme_dark_tertiaryContainer = Color(0xFF633E24)
val magenta_theme_dark_onTertiaryContainer = Color(0xFFFFDCC7)
val magenta_theme_dark_error = Color(0xFFFFB4AB)
val magenta_theme_dark_errorContainer = Color(0xFF93000A)
val magenta_theme_dark_onError = Color(0xFF690005)
val magenta_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val magenta_theme_dark_background = Color(0xFF1F1A1C)
val magenta_theme_dark_onBackground = Color(0xFFEBE0E2)
val magenta_theme_dark_surface = Color(0xFF1F1A1C)
val magenta_theme_dark_onSurface = Color(0xFFEBE0E2)
val magenta_theme_dark_surfaceVariant = Color(0xFF504348)
val magenta_theme_dark_onSurfaceVariant = Color(0xFFD4C2C7)
val magenta_theme_dark_outline = Color(0xFF9D8C92)
val magenta_theme_dark_inverseOnSurface = Color(0xFF1F1A1C)
val magenta_theme_dark_inverseSurface = Color(0xFFEBE0E2)
val magenta_theme_dark_inversePrimary = Color(0xFFA62E72)
val magenta_theme_dark_surfaceTint = Color(0xFFFFAFD2)


val magenta_seed = Color(0xFFF56EB3)
