package com.github.pakka_papad.ui.accent_colours.jacksons_purple

import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme


val JacksonsPurpleLightColors = lightColorScheme(
    primary = jacksons_purple_theme_light_primary,
    onPrimary = jacksons_purple_theme_light_onPrimary,
    primaryContainer = jacksons_purple_theme_light_primaryContainer,
    onPrimaryContainer = jacksons_purple_theme_light_onPrimaryContainer,
    secondary = jacksons_purple_theme_light_secondary,
    onSecondary = jacksons_purple_theme_light_onSecondary,
    secondaryContainer = jacksons_purple_theme_light_secondaryContainer,
    onSecondaryContainer = jacksons_purple_theme_light_onSecondaryContainer,
    tertiary = jacksons_purple_theme_light_tertiary,
    onTertiary = jacksons_purple_theme_light_onTertiary,
    tertiaryContainer = jacksons_purple_theme_light_tertiaryContainer,
    onTertiaryContainer = jacksons_purple_theme_light_onTertiaryContainer,
    error = jacksons_purple_theme_light_error,
    errorContainer = jacksons_purple_theme_light_errorContainer,
    onError = jacksons_purple_theme_light_onError,
    onErrorContainer = jacksons_purple_theme_light_onErrorContainer,
    background = jacksons_purple_theme_light_background,
    onBackground = jacksons_purple_theme_light_onBackground,
    surface = jacksons_purple_theme_light_surface,
    onSurface = jacksons_purple_theme_light_onSurface,
    surfaceVariant = jacksons_purple_theme_light_surfaceVariant,
    onSurfaceVariant = jacksons_purple_theme_light_onSurfaceVariant,
    outline = jacksons_purple_theme_light_outline,
    inverseOnSurface = jacksons_purple_theme_light_inverseOnSurface,
    inverseSurface = jacksons_purple_theme_light_inverseSurface,
    inversePrimary = jacksons_purple_theme_light_inversePrimary,
    surfaceTint = jacksons_purple_theme_light_surfaceTint,
)


val JacksonsPurpleDarkColors = darkColorScheme(
    primary = jacksons_purple_theme_dark_primary,
    onPrimary = jacksons_purple_theme_dark_onPrimary,
    primaryContainer = jacksons_purple_theme_dark_primaryContainer,
    onPrimaryContainer = jacksons_purple_theme_dark_onPrimaryContainer,
    secondary = jacksons_purple_theme_dark_secondary,
    onSecondary = jacksons_purple_theme_dark_onSecondary,
    secondaryContainer = jacksons_purple_theme_dark_secondaryContainer,
    onSecondaryContainer = jacksons_purple_theme_dark_onSecondaryContainer,
    tertiary = jacksons_purple_theme_dark_tertiary,
    onTertiary = jacksons_purple_theme_dark_onTertiary,
    tertiaryContainer = jacksons_purple_theme_dark_tertiaryContainer,
    onTertiaryContainer = jacksons_purple_theme_dark_onTertiaryContainer,
    error = jacksons_purple_theme_dark_error,
    errorContainer = jacksons_purple_theme_dark_errorContainer,
    onError = jacksons_purple_theme_dark_onError,
    onErrorContainer = jacksons_purple_theme_dark_onErrorContainer,
    background = jacksons_purple_theme_dark_background,
    onBackground = jacksons_purple_theme_dark_onBackground,
    surface = jacksons_purple_theme_dark_surface,
    onSurface = jacksons_purple_theme_dark_onSurface,
    surfaceVariant = jacksons_purple_theme_dark_surfaceVariant,
    onSurfaceVariant = jacksons_purple_theme_dark_onSurfaceVariant,
    outline = jacksons_purple_theme_dark_outline,
    inverseOnSurface = jacksons_purple_theme_dark_inverseOnSurface,
    inverseSurface = jacksons_purple_theme_dark_inverseSurface,
    inversePrimary = jacksons_purple_theme_dark_inversePrimary,
    surfaceTint = jacksons_purple_theme_dark_surfaceTint,
)