package com.github.pakka_papad.ui.accent_colours.melrose

import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme


val MelroseLightColors = lightColorScheme(
    primary = melrose_theme_light_primary,
    onPrimary = melrose_theme_light_onPrimary,
    primaryContainer = melrose_theme_light_primaryContainer,
    onPrimaryContainer = melrose_theme_light_onPrimaryContainer,
    secondary = melrose_theme_light_secondary,
    onSecondary = melrose_theme_light_onSecondary,
    secondaryContainer = melrose_theme_light_secondaryContainer,
    onSecondaryContainer = melrose_theme_light_onSecondaryContainer,
    tertiary = melrose_theme_light_tertiary,
    onTertiary = melrose_theme_light_onTertiary,
    tertiaryContainer = melrose_theme_light_tertiaryContainer,
    onTertiaryContainer = melrose_theme_light_onTertiaryContainer,
    error = melrose_theme_light_error,
    errorContainer = melrose_theme_light_errorContainer,
    onError = melrose_theme_light_onError,
    onErrorContainer = melrose_theme_light_onErrorContainer,
    background = melrose_theme_light_background,
    onBackground = melrose_theme_light_onBackground,
    surface = melrose_theme_light_surface,
    onSurface = melrose_theme_light_onSurface,
    surfaceVariant = melrose_theme_light_surfaceVariant,
    onSurfaceVariant = melrose_theme_light_onSurfaceVariant,
    outline = melrose_theme_light_outline,
    inverseOnSurface = melrose_theme_light_inverseOnSurface,
    inverseSurface = melrose_theme_light_inverseSurface,
    inversePrimary = melrose_theme_light_inversePrimary,
    surfaceTint = melrose_theme_light_surfaceTint,
)


val MelroseDarkColors = darkColorScheme(
    primary = melrose_theme_dark_primary,
    onPrimary = melrose_theme_dark_onPrimary,
    primaryContainer = melrose_theme_dark_primaryContainer,
    onPrimaryContainer = melrose_theme_dark_onPrimaryContainer,
    secondary = melrose_theme_dark_secondary,
    onSecondary = melrose_theme_dark_onSecondary,
    secondaryContainer = melrose_theme_dark_secondaryContainer,
    onSecondaryContainer = melrose_theme_dark_onSecondaryContainer,
    tertiary = melrose_theme_dark_tertiary,
    onTertiary = melrose_theme_dark_onTertiary,
    tertiaryContainer = melrose_theme_dark_tertiaryContainer,
    onTertiaryContainer = melrose_theme_dark_onTertiaryContainer,
    error = melrose_theme_dark_error,
    errorContainer = melrose_theme_dark_errorContainer,
    onError = melrose_theme_dark_onError,
    onErrorContainer = melrose_theme_dark_onErrorContainer,
    background = melrose_theme_dark_background,
    onBackground = melrose_theme_dark_onBackground,
    surface = melrose_theme_dark_surface,
    onSurface = melrose_theme_dark_onSurface,
    surfaceVariant = melrose_theme_dark_surfaceVariant,
    onSurfaceVariant = melrose_theme_dark_onSurfaceVariant,
    outline = melrose_theme_dark_outline,
    inverseOnSurface = melrose_theme_dark_inverseOnSurface,
    inverseSurface = melrose_theme_dark_inverseSurface,
    inversePrimary = melrose_theme_dark_inversePrimary,
    surfaceTint = melrose_theme_dark_surfaceTint,
)