package com.github.pakka_papad.ui.accent_colours.melrose
import androidx.compose.ui.graphics.Color

val melrose_theme_light_primary = Color(0xFF5D52A9)
val melrose_theme_light_onPrimary = Color(0xFFFFFFFF)
val melrose_theme_light_primaryContainer = Color(0xFFE5DEFF)
val melrose_theme_light_onPrimaryContainer = Color(0xFF180164)
val melrose_theme_light_secondary = Color(0xFF5F5C71)
val melrose_theme_light_onSecondary = Color(0xFFFFFFFF)
val melrose_theme_light_secondaryContainer = Color(0xFFE5DFF9)
val melrose_theme_light_onSecondaryContainer = Color(0xFF1B192C)
val melrose_theme_light_tertiary = Color(0xFF7B5265)
val melrose_theme_light_onTertiary = Color(0xFFFFFFFF)
val melrose_theme_light_tertiaryContainer = Color(0xFFFFD8E7)
val melrose_theme_light_onTertiaryContainer = Color(0xFF301121)
val melrose_theme_light_error = Color(0xFFBA1A1A)
val melrose_theme_light_errorContainer = Color(0xFFFFDAD6)
val melrose_theme_light_onError = Color(0xFFFFFFFF)
val melrose_theme_light_onErrorContainer = Color(0xFF410002)
val melrose_theme_light_background = Color(0xFFFFFBFF)
val melrose_theme_light_onBackground = Color(0xFF1C1B1F)
val melrose_theme_light_surface = Color(0xFFFFFBFF)
val melrose_theme_light_onSurface = Color(0xFF1C1B1F)
val melrose_theme_light_surfaceVariant = Color(0xFFE5E0EC)
val melrose_theme_light_onSurfaceVariant = Color(0xFF47464F)
val melrose_theme_light_outline = Color(0xFF78767F)
val melrose_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val melrose_theme_light_inverseSurface = Color(0xFF313034)
val melrose_theme_light_inversePrimary = Color(0xFFC7BFFF)
val melrose_theme_light_surfaceTint = Color(0xFF5D52A9)

val melrose_theme_dark_primary = Color(0xFFC7BFFF)
val melrose_theme_dark_onPrimary = Color(0xFF2E2177)
val melrose_theme_dark_primaryContainer = Color(0xFF453A8F)
val melrose_theme_dark_onPrimaryContainer = Color(0xFFE5DEFF)
val melrose_theme_dark_secondary = Color(0xFFC8C3DC)
val melrose_theme_dark_onSecondary = Color(0xFF312E41)
val melrose_theme_dark_secondaryContainer = Color(0xFF474459)
val melrose_theme_dark_onSecondaryContainer = Color(0xFFE5DFF9)
val melrose_theme_dark_tertiary = Color(0xFFECB8CE)
val melrose_theme_dark_onTertiary = Color(0xFF482536)
val melrose_theme_dark_tertiaryContainer = Color(0xFF613B4D)
val melrose_theme_dark_onTertiaryContainer = Color(0xFFFFD8E7)
val melrose_theme_dark_error = Color(0xFFFFB4AB)
val melrose_theme_dark_errorContainer = Color(0xFF93000A)
val melrose_theme_dark_onError = Color(0xFF690005)
val melrose_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val melrose_theme_dark_background = Color(0xFF1C1B1F)
val melrose_theme_dark_onBackground = Color(0xFFE5E1E6)
val melrose_theme_dark_surface = Color(0xFF1C1B1F)
val melrose_theme_dark_onSurface = Color(0xFFE5E1E6)
val melrose_theme_dark_surfaceVariant = Color(0xFF47464F)
val melrose_theme_dark_onSurfaceVariant = Color(0xFFC9C5D0)
val melrose_theme_dark_outline = Color(0xFF928F99)
val melrose_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val melrose_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val melrose_theme_dark_inversePrimary = Color(0xFF5D52A9)
val melrose_theme_dark_surfaceTint = Color(0xFFC7BFFF)


val melrose_seed = Color(0xFFADA2FF)
